#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-usv
#
# --------------------------------------------------------------------------

# --- defaults used during installation   ----------------------------------

PROJECT="pi-usv"

# --- basic packages   ------------------------------------------------------

PACKAGES=""
if [ -n "$PACKAGES" ]; then
  apt-get update
  apt-get -y install $PACKAGES
fi

# --- install specific files   ----------------------------------------------

rand="$RANDOM"
if [ -f /etc/${PROJECT}.conf ]; then
  # save current configuration
  mv /etc/${PROJECT}.conf /etc/${PROJECT}.conf.$rand
fi

for f in `find $(dirname "$0")/../files/ -type f`; do
  cp "$f" "${f#*files}"
  chown root:root "${f#*files}"
done
chmod 755 /usr/local/sbin/${PROJECT}*
chmod 644 /etc/${PROJECT}.conf
chmod 644 /etc/systemd/system/${PROJECT}.service

# restore old configuration
if [ -f /etc/${PROJECT}.conf.$rand ]; then
  mv -f /etc/${PROJECT}.conf /etc/${PROJECT}.conf.new
  mv /etc/${PROJECT}.conf.$rand /etc/${PROJECT}.conf
  echo -e "\nnew version of configuration file: /etc/${PROJECT}.conf.new"
fi

# --- activate service   ----------------------------------------------------

systemctl enable ${PROJECT}.service

# --- final configuration is manual   ---------------------------------------

echo -e "\nPlease edit /etc/${PROJECT}.conf and start ${PROJECT}.service"
